apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf-server
spec:
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - name: iperf
        image: networkstatic/iperf3
        command: ["/bin/sh", "-c"]
        args: ["iperf3 -s"] 
        ports:
        - containerPort: 5201 
      hostNetwork: true        