apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf-server
spec:
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - name: iperf
        image: networkstatic/iperf3
        command: ["/bin/bash", "-c"]
        args: ["for ((i=5201; i<=$MAX_PORT; i++)); do iperf3 -s -p $i; done"] 
        env:
        - name: MAX_PORT
          value: "5220"
      hostNetwork: true        