apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf-server
spec:
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - name: iperf
        image: networkstatic/iperf3
        command: ["/bin/bash"]
        args: ["-c","for ((i=5201 ; i<=$MAX_PORT-1;i++)); do iperf3 -s -p $i & echo \"port : $i\" ; done & iperf3 -s -p $MAX_PORT"] 
        env:
        - name: MAX_PORT
          value: "5210"
      hostNetwork: true        